### ISSUE TITLE
Enhance the Trailer Download Feature

### ISSUE THREAD

**Issue by JideGuru** [DroidGeeks/BigUpMovies#1]
Hello,
I was wondering if you would allow me to help make the download feature better.
I would use the Download manager other the a WebView with savefrom.net

Thanks

**Comment by JycTheDev** [comment]
Sure!! You highly welcome

**Comment by JideGuru** [comment]
Thanks.
i will be making a pull request tomorrow.

**Comment by JideGuru** [comment]
Ive made the pull request.
